### PR TITLE
add leaf class for inheritance

### PR DESCRIPTION
**Pull request by miltontony**

### CODE REVIEW

**Comment by miltontony** [comment]
Needs tests

**Comment by miltontony** [comment]
@smn review please
Inheritance magic

**Comment by smn** [comment]
Are you needing this to differentiate between controller types? Will zope.interface not give you better tools to do that with?

**Comment by miltontony** [comment]
No, I'm needing it in order to keep my base views very simple. So I can continue using `Controller.objects.all()` and using things like `controller.as_leaf_class().update_marathon_app()` without needing to care about overrides implemented on the child classes. If the child class overrides `update_marathon_app()`, it gets lost if I'm using `Controller.objects.all()`, in order to get to the child version, I'd have to user `ChildController.objects.all()` which I don't know about in the base views. The idea is that the implementation of Controllers can remain rather simple. Have a look at this [docker controller](https://github.com/miltontony/mc2/pull/5) implementation for how I intend controllers to be defined.

**Comment by smn** [comment]
:+1:

**Comment by miltontony** [comment]
@smn your question bugged me a bit so I went reading (again) on inheritance, zope.interfaces, polymorphism, etc. and I eventually found what I was looking for. The `as_leaf_class` is something I picked up when working in Jmbo and I thought it was niffty, but I've come to find that it's outdated. There are more _feng shui_ ways of doing it. Along comes [django-polymorphic](http://django-polymorphic.readthedocs.org/en/latest/index.html)

**Comment by miltontony** [comment]
@smn re-review please

**Comment by smn** [comment]
:+1:

**Pull request merged**
